export const conversions = [
  {category:'Weight',prompt:'1 pound = ___ ounces',correct:'16 ounces',alternates:['12 ounces','8 ounces','24 ounces'],tip:'A pound contains 16 ounces.'},
  {category:'Fractions',prompt:'3/8 = ___%',correct:'37.5%',alternates:['35%','32.5%','40%'],tip:'Each eighth equals 12.5%; 3 × 12.5 = 37.5.'},
  {category:'Volume',prompt:'1 cup = ___ fluid ounces',correct:'8 fluid ounces',alternates:['4 fluid ounces','12 fluid ounces','16 fluid ounces'],tip:'One cup holds 8 fluid ounces.'},
  {category:'Volume',prompt:'1 quart = ___ pints',correct:'2 pints',alternates:['4 pints','8 pints','16 pints'],tip:'Two pints make one quart.'},
  {category:'Fractions',prompt:'1/3 = ___%',correct:'33⅓%',alternates:['30%','25%','66⅔%'],tip:'One whole divided into three equal parts gives 33⅓% each.'},
  {category:'Distance',prompt:'1 mile = ___ feet',correct:'5,280 feet',alternates:['1,760 feet','3,600 feet','5,000 feet'],tip:'Memorize the exact mile conversion: 5,280 feet.'},
  {category:'Fractions',prompt:'5/8 = ___%',correct:'62.5%',alternates:['60%','57.5%','67.5%'],tip:'Each eighth is 12.5%; 5 × 12.5 = 62.5.'},
  {category:'Area',prompt:'1 square foot = ___ square inches',correct:'144 square inches',alternates:['12 square inches','36 square inches','120 square inches'],tip:'Area squares the conversion: 12 × 12 = 144.'},
  {category:'Fractions',prompt:'1/8 = ___%',correct:'12.5%',alternates:['8%','10%','15%'],tip:'Divide 100 by 8 to get 12.5.'},
  {category:'Fractions',prompt:'2/3 = ___%',correct:'66⅔%',alternates:['33⅓%','60%','75%'],tip:'Two thirds is twice 33⅓%.'},
  {category:'Counting',prompt:'1 dozen = ___ units',correct:'12 units',alternates:['10 units','24 units','144 units'],tip:'A dozen always means 12.'},
  {category:'Fractions',prompt:'7/8 = ___%',correct:'87.5%',alternates:['82.5%','85%','92.5%'],tip:'Seven groups of 12.5% equal 87.5%.'},
  {category:'Volume',prompt:'1 gallon = ___ quarts',correct:'4 quarts',alternates:['2 quarts','8 quarts','16 quarts'],tip:'Mr. Gallon has four quart sections.'},
  {category:'Fractions',prompt:'2/5 = ___%',correct:'40%',alternates:['20%','25%','50%'],tip:'Each fifth equals 20%; twice that is 40%.'},
  {category:'Distance',prompt:'1 yard = ___ feet',correct:'3 feet',alternates:['2 feet','6 feet','12 feet'],tip:'One yard is three feet.'},
  {category:'Fractions',prompt:'1/2 = ___%',correct:'50%',alternates:['25%','40%','75%'],tip:'One half of 100 is 50.'},
  {category:'Volume',prompt:'1 cubic yard = ___ cubic feet',correct:'27 cubic feet',alternates:['9 cubic feet','18 cubic feet','36 cubic feet'],tip:'Cube the yard conversion: 3 × 3 × 3 = 27.'},
  {category:'Multiplication',prompt:'8 × 6 = ___',correct:'48',alternates:['42','46','54'],tip:'Six groups of eight equal 48.'},
  {category:'Fractions',prompt:'1/6 = ___%',correct:'16⅔%',alternates:['17⅔%','12.5%','20%'],tip:'100 ÷ 6 = 16⅔%, not 17⅔%.'},
  {category:'Time',prompt:'1 day = ___ hours',correct:'24 hours',alternates:['12 hours','48 hours','60 hours'],tip:'A complete day has 24 hours.'},
  {category:'Area',prompt:'1 square yard = ___ square feet',correct:'9 square feet',alternates:['3 square feet','12 square feet','27 square feet'],tip:'Square the conversion: 3 feet × 3 feet = 9 square feet.'},
  {category:'Counting',prompt:'1 gross = ___ units',correct:'144 units',alternates:['12 units','100 units','1,440 units'],tip:'A gross is 12 dozen: 12 × 12 = 144.'},
  {category:'Volume',prompt:'1 gallon = ___ pints',correct:'8 pints',alternates:['2 pints','4 pints','16 pints'],tip:'Four quarts times two pints each equals eight pints.'},
  {category:'Distance',prompt:'1 foot = ___ inches',correct:'12 inches',alternates:['10 inches','24 inches','36 inches'],tip:'One foot is 12 inches, not 24.'},
  {category:'Fractions',prompt:'5/6 = ___%',correct:'83⅓%',alternates:['80%','85⅓%','86⅔%'],tip:'Five sixths is 100% − 16⅔% = 83⅓%.'},
  {category:'Weight',prompt:'1 ton = ___ pounds',correct:'2,000 pounds',alternates:['1,000 pounds','1,500 pounds','2,200 pounds'],tip:'A U.S. short ton equals 2,000 pounds.'},
  {category:'Distance',prompt:'1 yard = ___ inches',correct:'36 inches',alternates:['12 inches','24 inches','48 inches'],tip:'Three feet times 12 inches equals 36 inches.'},
  {category:'Multiplication',prompt:'9 × 7 = ___',correct:'63',alternates:['56','62','72'],tip:'Seven groups of nine equal 63.'},
  {category:'Volume',prompt:'1 pint = ___ cups',correct:'2 cups',alternates:['4 cups','8 cups','16 cups'],tip:'Two cups make one pint.'},
  {category:'Multiplication',prompt:'8 × 4 = ___',correct:'32',alternates:['28','36','42'],tip:'Four groups of eight equal 32.'},
  {category:'Time',prompt:'1 year = ___ months',correct:'12 months',alternates:['10 months','24 months','52 months'],tip:'A calendar year has 12 months.'},
  {category:'Multiplication',prompt:'6 × 9 = ___',correct:'54',alternates:['48','56','63'],tip:'Six groups of nine equal 54.'},
  {category:'Multiplication',prompt:'9 × 9 = ___',correct:'81',alternates:['72','80','90'],tip:'Nine squared equals 81.'},
  {category:'Multiplication',prompt:'8 × 8 = ___',correct:'64',alternates:['56','62','72'],tip:'Eight squared equals 64.'},
  {category:'Distance',prompt:'1 mile = ___ yards',correct:'1,760 yards',alternates:['1,000 yards','1,500 yards','5,280 yards'],tip:'A mile contains 1,760 yards.'},
  {category:'Multiplication',prompt:'7 × 7 = ___',correct:'49',alternates:['42','48','56'],tip:'Seven squared equals 49.'},
  {category:'Time',prompt:'1 year = ___ weeks',correct:'52 weeks',alternates:['48 weeks','50 weeks','60 weeks'],tip:'Use 52 weeks as the standard year conversion.'},
  {category:'Fractions',prompt:'1/5 = ___%',correct:'20%',alternates:['10%','25%','50%'],tip:'Divide 100 by 5 to get 20.'},
  {category:'Fractions',prompt:'1/4 = ___%',correct:'25%',alternates:['20%','40%','50%'],tip:'One quarter of 100 is 25.'},
  {category:'Time',prompt:'1 hour = ___ minutes',correct:'60 minutes',alternates:['30 minutes','90 minutes','100 minutes'],tip:'One hour contains 60 minutes.'},
  {category:'Time',prompt:'1 week = ___ days',correct:'7 days',alternates:['5 days','10 days','14 days'],tip:'A complete week has seven days.'},
  {category:'Multiplication',prompt:'7 × 4 = ___',correct:'28',alternates:['24','32','35'],tip:'Four groups of seven equal 28.'},
  {category:'Time',prompt:'1 common year = ___ days',correct:'365 days',alternates:['360 days','364 days','366 days'],tip:'A common year has 365 days; a leap year has 366.'},
  {category:'Fractions',prompt:'3/5 = ___%',correct:'60%',alternates:['40%','50%','75%'],tip:'Each fifth is 20%; three fifths equal 60%.'}
];

export default conversions;
