const baseChapters=[
{era:'Before time',title:'1. The Garden and the First Argument',text:`The lore book Unveiling describes an allegorical garden. The Gardener became an [[advocate]] for complexity; the Winnower favored a final, stable pattern. Their disagreement became a cosmic [[schism]]. The Gardener’s experiment seemed [[impetuous]] to its opponent, so a [[prudent]] reader remembers that this [[ubiquitous]] conflict is philosophy told by the Darkness, not a neutral eyewitness report.`,q:'How should the Garden story be interpreted?',a:['As an allegory','As a Cabal report','As human history'],c:0},
{era:'Eons before humanity',title:'2. The Birth of the Witness',text:`A distant people found the Traveler and received a [[plethora]] of knowledge, yet its silence left them in a [[quandary]]. Growing [[scornful]], they found the Veil and tried to [[devise]] one permanent purpose for reality. Their [[shrewd]] plan failed when the Traveler fled. They then merged themselves into the [[erudite]] Witness. This [[canny]] being pursued the Traveler and sought to [[suppress]] possibility through the Final Shape.`,q:'Why was the Witness created?',a:['To impose meaning and order','To build Ghosts','To defend Riis'],c:0},
{era:'Billions of years ago',title:'3. Fundament and the Hive',text:`On Fundament, Aurash, Sathona, and Xi Ro feared an [[imminent]] God-Wave. The Worm Gods offered power, but their hunger guaranteed endless [[attrition]]. Reborn as Oryx, Savathûn, and Xivu Arath, they learned to [[abhor]] weakness and [[assail]] civilizations. The Witness and Rhulk could [[feign]] salvation while hiding their real purpose; the Hive became the [[bane]] of worlds as their freedom began to [[dwindle]].`,q:'What was the cost of the worms’ bargain?',a:['Ever-growing hunger','Loss of all weapons','Human exile'],c:0},
{era:'Ancient civilizations',title:'4. Riis and the Disciples',text:`The Traveler uplifted the Eliksni on Riis, but the Whirlwind left their society [[depleted]]. Some later [[boast]] of strength while others preserve [[homage]] to the Great Machine. The Witness recruited Disciples such as Rhulk and Nezarec; Calus served it with theatrical [[fervor]], unaware that every Disciple was merely a disposable tool.`,q:'What was the Whirlwind?',a:['The fall of Eliksni civilization','A Vex engine','A human war'],c:0},
{era:'Humanity’s future',title:'5. The Golden Age',text:`Humanity met the Traveler on Mars and became an [[agile]] spacefaring civilization. Each new [[acquisition]] of knowledge carried opportunity and danger. Scientists tried to [[glean]] every secret. Clovis Bray pursued Exo immortality without [[qualm]] and would even [[embezzle]] human dignity for his experiments, while Vex simulations created a profound [[predicament]] for the Ishtar Collective. An [[impartial]] account must recognize both the miracles and their cost. A [[latent]] Darkness influence waited inside the K1 artifact on the Moon.`,q:'What began after humanity met the Traveler?',a:['The Golden Age','The Red War','The Dark Age'],c:0},
{era:'End of the Golden Age',title:'6. The Collapse',text:`The Black Fleet arrived, and Rasputin could not [[quell]] it. A frightened [[throng]] gathered beneath the Traveler while [[livid]] and [[demoralized]] survivors lived in [[makeshift]] shelters with a [[dearth]] of food and medicine. Savathûn betrayed Nezarec and hid the Veil on Neptune; the Traveler repelled the attack, then hung [[wan]] and silent above Earth. It created Ghosts, but the [[austere]] Dark Age left humanity in [[destitution]] and its population began to [[plummet]].`,q:'What did the Traveler create after its stand?',a:['Ghosts','The Vex','The Cabal'],c:0},
{era:'Centuries after the Collapse',title:'7. Warlords and the Last City',text:`Some early Risen ruled through raw [[brawn]], making civilians [[wince]] at their approach. The Iron Lords fought those Warlords and tried to restore [[decorum]], but SIVA destroyed nearly all of them. Refugees built the Last City beneath the Traveler; at Twilight Gap, Guardians prevented humanity’s [[ouster]] from its final home.`,q:'Whom did the Iron Lords oppose?',a:['The Warlords','The Cloud Striders','The Techeuns'],c:0},
{era:'Destiny 1',title:'8. The Young Wolf and Oryx',text:`A Ghost raised the Guardian in the Cosmodrome. The new Lightbearer helped [[decipher]] the Vex threat and destroyed the Black Heart. After Crota fell, Oryx invaded and inflicted terrible [[attrition]] on the Awoken. The Guardian refused the [[acquisition]] of Oryx’s throne. Later, SIVA spread like a [[virulent]] infection through the Devil Splicers. After defeating that crisis, Saladin chose to [[commend]] the Guardian as a new Iron Lord.`,q:'Why did Oryx invade the Solar System?',a:['To avenge Crota','To meet Ghaul','To find the Veil'],c:0},
{era:'Red War to Forsaken',title:'9. Ghaul, Osiris, and Cayde-6',text:`Ghaul caged the Traveler, forcing a [[hiatus]] in the Guardians’ Light, and demanded that it [[cede]] power to him. Later, Zavala was [[hesitant]] and began to [[vacillate]] between distrusting Rasputin and accepting his assistance, but he had to [[concur]] that the Warmind would act independently. Cayde-6’s murder began a [[contentious]] hunt for Uldren, who died and later returned without memories as Crow.`,q:'What alerted the distant Black Fleet?',a:['The Traveler’s pulse','Cayde’s death','A Vex message'],c:0},
{era:'Shadowkeep to The Witch Queen',title:'10. Learning to Use Darkness',text:`The lunar Pyramid became a psychological [[hindrance]]. On Europa, the Guardian learned Stasis while avoiding an [[erratic]] path toward corruption. Savathûn impersonated Osiris to [[elicit]] secrets and later received the Light from a Ghost. That truth was an [[admonition]]: the Vanguard did not fully understand the Traveler. The Witness had deceived the Hive from the beginning.`,q:'How did Savathûn receive the Light?',a:['A Ghost resurrected her','She stole it from Ghaul','Oryx gave it to her'],c:0},
{era:'The Coalition',title:'11. Former Enemies Become Allies',text:`Mithrax and the House of Light found an [[abode]] in the City, exposing prejudice and political [[nepotism]]. Saint-14 became an [[unpretentious]] ally, while Crow’s [[nonchalant]] exterior hid deep guilt. Some citizens called cooperation a [[sham]] and continued to [[gawk]] at former enemies. Yet the old [[adage]] that enemies can never change proved false: the Coalition showed that conflict need not end with one survivor.`,q:'What did the Coalition demonstrate?',a:['Enemies can choose cooperation','Only one species can live','The Traveler controls everyone'],c:0},
{era:'Lightfall',title:'12. Neptune and Strand',text:`Osiris began an [[impromptu]] pursuit of Calus to Neomuna. Its neon surface could look [[tawdry]] amid invasion, yet its people possessed advanced technology. Osiris’s [[inquisitive]] mind helped the Guardian understand Strand. Calus was the opposite of [[abstemious]]—he desired endless pleasure and would [[ogle]] every treasure and display of luxury. The Witness used Ghost and the Veil to open a portal in the Traveler.`,q:'How did the Guardian master Strand?',a:['By accepting its flow','By rejecting Darkness','Through physical strength'],c:0},
{era:'The Final Shape',title:'13. The Pale Heart',text:`Inside the Traveler, the Witness offered a [[terse]] promise: surrender choice and end suffering. Zavala refused to [[writhe]] forever beneath grief. The dissenting minds within the Witness helped the Guardian weaken it. The final victory was not an [[embargo]] on Darkness; Light and Darkness could coexist. Cayde’s farewell carried no [[reprimand]], only trust. The Witness fell, but the future remained open.`,q:'What made the Witness vulnerable?',a:['The dissenting minds within it','Ghaul’s cage','Neptune’s destruction'],c:0}
];

const enrichment=[
`The struggle would [[precede]] every civilization later known to Guardians. Unveiling often [[allude]]s to rules and flowers, but readers may [[construe]] those images in different ways.`,
`The Precursors held the [[conviction]] that existence required a single purpose. The Final Shape was a [[tantalizing]] promise, but its central [[flaw]] was the destruction of freedom. Their combined consciousness would [[materialize]] as the Witness.`,
`The claimed God-Wave served as an [[omen]] of destruction. The Witness used that fear to [[bamboozle]] the siblings, converting desperation into endless [[loathing]] for weakness.`,
`The Whirlwind appeared to [[maroon]] the Eliksni among the ruins of Riis. The Traveler remained [[elusive]], while the Witness continued its [[unrelenting]] pursuit across the stars.`,
`Golden Age research was [[eclectic]], combining medicine, artificial intelligence, spaceflight, and paracausal science. The Traveler transformed once [[sterile]] worlds. Later, every [[allegation]] concerning Clovis Bray’s abuses seemed more believable as his records were uncovered.`,
`A [[somber]] silence followed the destruction. Refugees crossed ruined Earth [[laden]] with their remaining possessions, and even a fortified [[enclosure]] offered little safety. Many communities possessed barely an [[iota]] of their former technology.`,
`[[Stalwart]] defenders protected small settlements with remarkable [[tenacity]]. The hope of a City beneath the Traveler helped [[invigorate]] people who had survived generations of fear.`,
`The Vex always searched for a [[flaw]] in every defense. Saladin found it painful to [[broach]] the subject of SIVA, whose [[virulent]] replication had destroyed his fellow Iron Lords.`,
`Vanguard scouts would [[canvass]] threatened regions before major operations. Ignoring those reports would have been [[negligent]]. The Guardian’s repeated arrival at crucial moments seemed almost too [[coincidental]] to be chance.`,
`Nightmares could [[materialize]] from grief, while Savathûn’s true intentions remained [[elusive]]. Her messages would [[allude]] to truths without explaining them directly.`,
`Lakshmi tried to [[flatter]] the City while feeding its fear. Away from politics, Eliksni hatchlings could [[frolic]] and [[gambol]] safely; peaceful life was never [[boring]] to people who had known only war.`,
`Calus pursued [[rapture]] through consumption and spectacle. He celebrated [[lewd]] excess, tried to [[finagle]] his way into the Witness’s favor, and would [[mope]] whenever admiration was denied.`,
`The Coalition’s connection through the portal was [[tenuous]], but its advance was [[unrelenting]]. Not one [[iota]] of certainty guaranteed victory; the allies succeeded through sacrifice and trust.`
];

export const loreChapters=baseChapters.map((chapter,index)=>({...chapter,text:`${chapter.text} ${enrichment[index]}`}));
export default loreChapters;
