import React,{useEffect,useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{BookOpen,Brain,Calculator,ChevronLeft,ChevronRight,Flame,Layers,RotateCcw,Target,Timer,Volume2,X,Zap}from'lucide-react';
import'./style.css';
import'./lore.css';
import'./media.css';
import'./conversions.css';
import'./hardWords.css';
import bsep from'./bsep.js';
import loreChapters from'./lore.js';
import divisionChapters from'./divisionLore.js';
import division1Chapters from'./division1Lore.js';
import conversions from'./conversions.js';
import{selectHardWords}from'./hardWords.js';

const KEY='bsep-progress-v1';
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return{}}};
function App(){
 const[mode,setMode]=useState(null),[progress,setProgress]=useState(load),[current,setCurrent]=useState(null),[choices,setChoices]=useState([]),[picked,setPicked]=useState(null),[flipped,setFlipped]=useState(false),[score,setScore]=useState(0),[streak,setStreak]=useState(0),[lives,setLives]=useState(3),[time,setTime]=useState(12),[chapter,setChapter]=useState(0);
 useEffect(()=>localStorage.setItem(KEY,JSON.stringify(progress)),[progress]);
 const stats=useMemo(()=>{let seen=0,mastered=0,errors=0;Object.values(progress).forEach(x=>{seen++;errors+=x.wrong||0;if((x.right||0)>=5&&(x.wrong||0)<=1)mastered++});return{seen,mastered,errors}},[progress]);
 const choose=()=>{const weighted=bsep.flatMap(w=>{const p=progress[w.word]||{};return Array(Math.max(1,4+(p.wrong||0)*2-(p.right||0))).fill(w)});const w=weighted[Math.floor(Math.random()*weighted.length)];setCurrent(w);setChoices(shuffle([w.correct,...w.alternates]).slice(0,4));setPicked(null);setFlipped(false);setTime(12)};
 useEffect(()=>{if(mode&&!['destiny','division1','division','conversions','hardwords'].includes(mode))choose()},[mode]);
 useEffect(()=>{if(mode!=='speed'||picked)return;const id=setInterval(()=>setTime(t=>{if(t<=1){answer('__timeout');return 12}return t-1}),1000);return()=>clearInterval(id)},[mode,current,picked]);
 const answer=value=>{if(picked)return;const ok=value===current.correct;setPicked(value);setScore(s=>s+(ok?100+streak*10:0));setStreak(s=>ok?s+1:0);if(mode==='survival'&&!ok)setLives(l=>l-1);setProgress(p=>({...p,[current.word]:{right:(p[current.word]?.right||0)+(ok?1:0),wrong:(p[current.word]?.wrong||0)+(ok?0:1),last:Date.now()}}))};
 const next=()=>{if(mode==='survival'&&lives<=0){setMode(null);setLives(3);return}choose()};
 const speak=()=>speechSynthesis.speak(new SpeechSynthesisUtterance(current.word.split('/')[0].trim()));
 if(!mode)return <main><header><div className="brand"><Brain/> BSEP Trainer</div><button className="ghost" onClick={()=>{if(confirm('¿Borrar todo tu progreso?')){localStorage.removeItem(KEY);localStorage.removeItem('conversion-progress-v1');localStorage.removeItem('hardwords-progress-v1');setProgress({})}}}><RotateCcw/> Reiniciar</button></header><section className="intro"><span className="eyebrow">ENTRENAMIENTO ADAPTATIVO</span><h1>Domina el vocabulario.<br/><em>Una palabra a la vez.</em></h1><p>Las palabras que fallas regresan con más frecuencia hasta que las domines.</p></section><section className="stats"><Stat n={stats.mastered} t="Dominadas"/><Stat n={stats.seen} t="Practicadas"/><Stat n={stats.errors} t="Errores por vencer"/></section><section className="modes"><Mode icon={<BookOpen/>} title="Historia de Destiny" text="Lore cronológico + palabras marcadas" onClick={()=>{setChapter(0);setMode('destiny')}}/><Mode icon={<BookOpen/>} title="Historia de The Division 1" text="Historia completa + vocabulario Destiny" onClick={()=>{setChapter(0);setMode('division1')}}/><Mode icon={<BookOpen/>} title="Historia de The Division 2" text="Primera parte + palabras nuevas" onClick={()=>{setChapter(0);setMode('division')}}/><Mode icon={<Target/>} title="Mis palabras difíciles" text="63 palabras que sigues fallando" onClick={()=>setMode('hardwords')}/><Mode icon={<Calculator/>} title="Conversiones rápidas" text="44 preguntas de la hoja" onClick={()=>setMode('conversions')}/><Mode icon={<Zap/>} title="Práctica BSEP" text="Selección múltiple adaptativa" onClick={()=>setMode('quiz')}/><Mode icon={<Layers/>} title="Flashcards" text="Recuerda antes de voltear" onClick={()=>setMode('cards')}/><Mode icon={<Timer/>} title="Speed Round" text="12 segundos por palabra" onClick={()=>setMode('speed')}/><Mode icon={<Flame/>} title="Survival" text="Tres vidas. Máxima concentración." onClick={()=>{setLives(3);setMode('survival')}}/></section><footer>{bsep.length} palabras · {conversions.length} conversiones · 63 palabras difíciles · Progreso guardado en este dispositivo</footer></main>;
 if(mode==='destiny')return <Lore chapters={loreChapters} chapter={chapter} setChapter={setChapter} exit={()=>setMode(null)}/>;
 if(mode==='division1')return <Lore chapters={division1Chapters} chapter={chapter} setChapter={setChapter} exit={()=>setMode(null)}/>;
 if(mode==='division')return <Lore chapters={divisionChapters} chapter={chapter} setChapter={setChapter} exit={()=>setMode(null)} incomplete/>;
 if(mode==='conversions')return <ConversionQuiz exit={()=>setMode(null)}/>;
 if(mode==='hardwords')return <HardWordsQuiz exit={()=>setMode(null)}/>;
 if(!current)return null;
 const p=progress[current.word]||{},level=(p.right||0)>=5?'Dominada':(p.right||0)>=2?'Aprendiendo':'Nueva';
 if(mode==='cards')return <main className="play"><Top/><div className={'flash '+(flipped?'turned':'')} onClick={()=>setFlipped(!flipped)}><span>{flipped?'SIGNIFICADO':'PALABRA'}</span><h2>{flipped?current.correct:current.word}</h2>{flipped&&<><p>{current.spanish}</p><small>{current.meaning}</small></>}<b>{flipped?'Toca para ocultar':'Piensa la respuesta y toca para revelar'}</b></div>{flipped&&<div className="rate"><button onClick={()=>{answer('wrong');next()}}>No la sabía</button><button className="primary" onClick={()=>{answer(current.correct);next()}}>La sabía</button></div>}</main>;
 function Top(){return <header><button className="ghost" onClick={()=>setMode(null)}><X/> Salir</button><div className="score">{mode==='survival'&&'❤️'.repeat(lives)} {mode==='speed'&&`⏱ ${time}s`} · {score} pts · 🔥 {streak}</div></header>}
 return <main className="play"><Top/><div className="meter"><span style={{width:`${time/12*100}%`}}/></div><section className="question"><div className="question-head"><span>{level}</span><button onClick={speak}><Volume2/></button></div><h2>{current.word}</h2><p>most nearly means:</p><div className="choices">{choices.map(c=><button key={c} disabled={!!picked} className={picked?(c===current.correct?'correct':c===picked?'wrong':''):''} onClick={()=>answer(c)}>{c}</button>)}</div>{picked&&<div className="feedback"><h3>{picked===current.correct?'✓ Correcto':'✕ Sigue practicando'}</h3><strong>{current.word} = {current.correct}</strong><p>{current.spanish}</p><p>{current.meaning}</p><div className="roots">{current.prefix&&<span>Prefijo: {current.prefix}</span>}{current.root&&<span>Raíz: {current.root}</span>}{current.suffix&&<span>Sufijo: {current.suffix}</span>}</div><blockquote>“{current.example}”</blockquote><button className="primary" onClick={next}>{mode==='survival'&&lives<=0?'Ver resultado':'Siguiente palabra →'}</button></div>}</section></main>
}
function Stat({n,t}){return <div><strong>{n}</strong><span>{t}</span></div>};function Mode({icon,title,text,onClick}){return <button className="mode" onClick={onClick}><i>{icon}</i><div><strong>{title}</strong><span>{text}</span></div><b>→</b></button>}
function HardWordsQuiz({exit}){
 const HKEY='hardwords-progress-v1';
 const words=useMemo(()=>selectHardWords(bsep),[]);
 const readProgress=()=>{try{return JSON.parse(localStorage.getItem(HKEY))||{}}catch{return{}}};
 const[hardProgress,setHardProgress]=useState(readProgress),[current,setCurrent]=useState(null),[options,setOptions]=useState([]),[picked,setPicked]=useState(null),[score,setScore]=useState(0),[streak,setStreak]=useState(0),[answered,setAnswered]=useState(0);
 const mastered=Object.values(hardProgress).filter(x=>(x.right||0)>=4&&(x.wrong||0)<=1).length;
 const chooseQuestion=()=>{const pool=words.flatMap(word=>{const p=hardProgress[word.quizWord]||{};return Array(Math.max(1,4+(p.wrong||0)*3-(p.right||0))).fill(word)});let word=pool[Math.floor(Math.random()*pool.length)];if(pool.length>1&&word===current)word=pool[(pool.indexOf(word)+1)%pool.length];setCurrent(word);setOptions(shuffle([word.correct,...word.alternates]));setPicked(null)};
 useEffect(()=>chooseQuestion(),[]);
 useEffect(()=>localStorage.setItem(HKEY,JSON.stringify(hardProgress)),[hardProgress]);
 const answer=value=>{if(picked)return;const ok=value===current.correct;setPicked(value);setAnswered(n=>n+1);setScore(n=>n+(ok?100+streak*10:0));setStreak(n=>ok?n+1:0);setHardProgress(p=>({...p,[current.quizWord]:{right:(p[current.quizWord]?.right||0)+(ok?1:0),wrong:(p[current.quizWord]?.wrong||0)+(ok?0:1)}}))};
 const speak=()=>speechSynthesis.speak(new SpeechSynthesisUtterance(current.quizWord));
 if(!current)return null;
 const p=hardProgress[current.quizWord]||{};
 return <main className="play"><header><button className="ghost" onClick={exit}><X/> Salir</button><div className="score">{score} pts · 🔥 {streak}</div></header><section className="question hardword-question"><div className="question-head"><span className="hardword-label">REPASO EXCLUSIVO</span><button onClick={speak} aria-label={`Escuchar ${current.quizWord}`}><Volume2/></button></div><div className="hardword-stats"><span>Pregunta {answered+1}</span><span>{mastered}/{words.length} dominadas</span><span>Fallos: {p.wrong||0}</span></div><h2>{current.quizWord}</h2><p>most nearly means:</p><div className="choices">{options.map(option=><button key={option} disabled={picked!==null} className={picked?(option===current.correct?'correct':option===picked?'wrong':''):''} onClick={()=>answer(option)}>{option}</button>)}</div>{picked&&<div className="feedback"><h3>{picked===current.correct?'✓ Correcto':'✕ Esta palabra regresará más pronto'}</h3><p className="hardword-answer"><strong>{current.quizWord} = {current.correct}</strong></p><p className="hardword-spanish">{current.spanish}</p><p>{current.meaning}</p><blockquote>“{current.example}”</blockquote><div className="hardword-actions"><button onClick={exit}>Terminar</button><button className="primary" onClick={chooseQuestion}>Siguiente palabra →</button></div></div>}</section><p className="conversion-progress">Las palabras que fallas reciben tres veces más peso. El progreso se guarda automáticamente.</p></main>
}
function ConversionQuiz({exit}){
 const CKEY='conversion-progress-v1';
 const readProgress=()=>{try{return JSON.parse(localStorage.getItem(CKEY))||{}}catch{return{}}};
 const[conversionProgress,setConversionProgress]=useState(readProgress),[current,setCurrent]=useState(null),[options,setOptions]=useState([]),[picked,setPicked]=useState(null),[score,setScore]=useState(0),[streak,setStreak]=useState(0),[answered,setAnswered]=useState(0);
 const mastered=Object.values(conversionProgress).filter(x=>(x.right||0)>=3&&(x.wrong||0)<=1).length;
 const chooseQuestion=()=>{const pool=conversions.flatMap(q=>{const p=conversionProgress[q.prompt]||{};return Array(Math.max(1,4+(p.wrong||0)*2-(p.right||0))).fill(q)});let q=pool[Math.floor(Math.random()*pool.length)];if(pool.length>1&&q===current)q=pool[(pool.indexOf(q)+1)%pool.length];setCurrent(q);setOptions(shuffle([q.correct,...q.alternates]));setPicked(null)};
 useEffect(()=>chooseQuestion(),[]);
 useEffect(()=>localStorage.setItem(CKEY,JSON.stringify(conversionProgress)),[conversionProgress]);
 const answer=value=>{if(picked)return;const ok=value===current.correct;setPicked(value);setAnswered(n=>n+1);setScore(n=>n+(ok?100+streak*10:0));setStreak(n=>ok?n+1:0);setConversionProgress(p=>({...p,[current.prompt]:{right:(p[current.prompt]?.right||0)+(ok?1:0),wrong:(p[current.prompt]?.wrong||0)+(ok?0:1)}}))};
 if(!current)return null;
 return <main className="play"><header><button className="ghost" onClick={exit}><X/> Salir</button><div className="score">{score} pts · 🔥 {streak}</div></header><section className="question conversion-question"><div className="question-head"><span>{current.category}</span><span>{mastered}/{conversions.length} dominadas</span></div><div className="conversion-meta"><span>Pregunta {answered+1}</span><span>Las falladas regresan más</span></div><h2>{current.prompt}</h2><div className="choices">{options.map(option=><button key={option} disabled={picked!==null} className={picked?(option===current.correct?'correct':option===picked?'wrong':''):''} onClick={()=>answer(option)}>{option}</button>)}</div>{picked&&<div className="feedback"><h3>{picked===current.correct?'✓ Correcto':'✕ Repásala otra vez'}</h3><p className="conversion-answer"><strong>{current.prompt.replace('___',current.correct)}</strong></p><p className="conversion-tip">Truco: {current.tip}</p><div className="conversion-actions"><button onClick={exit}>Terminar</button><button className="primary" onClick={chooseQuestion}>Siguiente pregunta →</button></div></div>}</section><p className="conversion-progress">El progreso se guarda automáticamente en este dispositivo.</p></main>
}
function Lore({chapters,chapter,setChapter,exit,incomplete=false}){
 const item=chapters[chapter];const[selected,setSelected]=useState(null),[quiz,setQuiz]=useState(null);
 const findWord=token=>bsep.find(w=>w.word.toLowerCase().split('/').some(x=>x.trim()===token.toLowerCase()))||{word:token,correct:'',spanish:''};
 const render=text=>text.split(/\[\[(.*?)\]\]/g).map((part,i)=>i%2?<button key={i} className="vocab" onClick={()=>setSelected(findWord(part))}>{part.toUpperCase()} <small>({findWord(part).correct})</small></button>:part);
 const move=n=>{setChapter(Math.max(0,Math.min(chapters.length-1,chapter+n)));setSelected(null);setQuiz(null);scrollTo(0,0)};
 return <main className="lore"><header><button className="ghost" onClick={exit}><X/> Salir</button><div className="score">Capítulo {chapter+1} de {chapters.length}{incomplete?' · Primera parte':''}</div></header><div className="lore-layout"><aside><span className="eyebrow">CRONOLOGÍA</span>{chapters.map((c,i)=><button className={i===chapter?'active':''} onClick={()=>{setChapter(i);setSelected(null);setQuiz(null)}} key={c.title}><b>{i+1}</b><span>{c.title.replace(/^\d+\. /,'')}</span></button>)}</aside><article><span className="era">{item.era}</span><h1>{item.title}</h1>{item.image&&<figure className="chapter-media"><img src={item.image} alt={`Ilustración del capítulo ${item.title}`} loading="eager"/></figure>}{item.audio&&<section className="audio-card"><div><strong>Escucha mientras lees</strong><span>Audio del capítulo {chapter+1}</span></div><audio key={item.audio} controls preload="metadata" src={item.audio}>Tu navegador no puede reproducir este audio.</audio></section>}<p className="hint">Las palabras azules son vocabulario BSEP. Tócalas para estudiarlas.</p><p className="story">{render(item.text)}</p>{selected&&<section className="word-note"><button className="close-note" onClick={()=>setSelected(null)}>×</button><span>PALABRA BSEP</span><h2>{selected.word}</h2><strong>{selected.correct} · {selected.spanish}</strong><p>{selected.meaning}</p></section>}<section className="chapter-quiz"><span>COMPRUEBA TU COMPRENSIÓN</span><h2>{item.q}</h2>{item.a.map((a,i)=><button className={quiz!==null?(i===item.c?'correct':i===quiz?'wrong':''):''} disabled={quiz!==null} onClick={()=>setQuiz(i)} key={a}>{a}</button>)}{quiz!==null&&<p>{quiz===item.c?'✓ Correcto. Comprendiste el capítulo.':'✕ Repasa el capítulo e inténtalo nuevamente.'}</p>}</section><nav><button disabled={!chapter} onClick={()=>move(-1)}><ChevronLeft/> Anterior</button><button disabled={chapter===chapters.length-1} onClick={()=>move(1)}>Siguiente <ChevronRight/></button></nav><small className="lore-note">Adaptación educativa y resumida.{incomplete?' Esta es la primera parte; la cronología continuará con nuevas palabras.':' Algunos relatos cosmológicos son alegóricos o proceden de narradores no confiables dentro del universo.'}</small></article></div></main>
}
createRoot(document.getElementById('root')).render(<App/>);

if('serviceWorker'in navigator){
  window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
}
